"""
Configuration File For input and output
"""

class IOConfiguration:

    URL = "https://www.surveymonkey.com"
    userName ="mangesh.khude"
    password = "infoserver123"

    # Questions
    emailQuestion = "Enter your email?"
    useSurveyMonkey = "How often do you use SurveyMonkey?"
    fromWhen = "From When are you using SurveyMonkey?"
    ratings = "How will rate the ease of survey creation?"
    meaningfulData = "Did you get meaningful data from survey analysis?"
    features = "Check the Features you like about SurveyMonkey?"
    questionBank = "QUESTION BANK"
    themes = "THEMES"
    graphical = "GRAPHICAL"
    result = "RESULT"
    template = "TEMPLATE RE-USABILITY"
    collectors = "COLLECTORS"
    service = "SERVICE"
    support = "SUPPORT"
    responsive = "RESPONSIVE"
    veryGood = "VERY GOOD"
    good = "GOOD"
    avarage = "AVARAGE"
    belowAvarage = "BELOW AVARAGE"
    rateFeatures = "Rate our features."
    mostLikedFeatures = "List the features you like most."
    recomendToFriends = "Will recommend SurveyMonkey to your friends / Colleagues?"
    commentsFeedback = "Comments / Feedback"
    featureList = "List the features you like most."